/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.wildcodeschool.sea8.exercise.junit_jupiter_getting_started;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AltesLandApfelTest {
    @Test
    public void classCheckAltesLandApfel() {

    // Apfel Objekte erstellen
    Apfel apfel1 = new Apfel("Elstar");        
    Apfel apfel2 = new Apfel("Holsteiner Cox");        
    Apfel apfel3 = new Apfel("Zari");        

   

    // Erstellen eines Objet Generics Liste

    AltesLandApfel<Apfel> ObstbauerElke = new AltesLandApfel<>();
    
    // Test Liste ohne Apfelsorte
   
    assertNotNull(ObstbauerElke);
    
    // Liste befüllen mit drei sorte

    ObstbauerElke.setApfel(apfel1);
    ObstbauerElke.setApfel(apfel2);
    ObstbauerElke.setApfel(apfel3);


    // Test erstes Element
    assertEquals("Elstar", ObstbauerElke.getFirstApfel().apfelsorte, "Elke hat Elstar");

    // Test letztes Element
    assertEquals("Zari", ObstbauerElke.getLastApfel().apfelsorte, "Elke hat Zari");    

    }
}
